# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: 
- develop

pr: none

resources:
  repositories:
  - repository: templates
    type: github
    name: cchanka/azdo-pipeline-templates
    endpoint: GitHub connection - cchanka


stages:
- template: build-dev-pipeline-template.yml@templates
  parameters:
    appVersionMajor: $(app_ver_major)
    appVersionMinor: $(app_ver_minor)
    appVersionPatch: $(app_ver_patch)
    appVersionCode: $(Build.BuildId)
    appFilePath: $(System.DefaultWorkingDirectory)/app/build/outputs/apk/app-prod-debug.apk
    appCenterServiceConnection: $(APPCENTER_SC_NAME)
    appCenterAppSlug: $(APPCENTER_APP_SLUG)
    appCenterDistributionGroupIDs: $(APPCENTER_DIST_GROUP_IDS)
    vmImage: macOS-10.14
