# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: 
- develop

pr: none

pool:
  vmImage: 'macOS-10.14'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    tasks: 'assembleDebug'
  displayName: gradlew assembleDebug
  
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk'
    apksignerKeystoreFile: 'testingks.jks'
    apksignerKeystorePassword: '$(keystorepassword)'
    apksignerKeystoreAlias: '$(keyalias)'
    apksignerKeyPassword: '$(keypassword)'
    zipalign: false

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'TODOAPP-APP-CENTER'
    appSlug: 'cchanka/TODOAPP-CHANKA'
    appFile: '$(System.DefaultWorkingDirectory)/app/build/outputs/apk/app-prod-debug.apk'
    symbolsOption: 'Android'
    releaseNotesOption: 'input'
    releaseNotesInput: 'DEV Release from Azure DevOps'
    destinationType: 'groups'
    distributionGroupId: 'fa5af56c-dfed-4298-820d-0ac72bffbd20'

# - task: CopyFiles@2
#   inputs:
#     contents: '**/*.apk'
#     targetFolder: '$(build.artifactStagingDirectory)'
#   displayName: Copy .apk files to artifact staging directory

# - task: PublishBuildArtifacts@1
#   inputs:
#     pathToPublish: '$(build.artifactStagingDirectory)'
#     artifactName: 'drop'
#     artifactType: 'container'
#   displayName: Publish artifacts