# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: 
- develop

pr: none

pool:
  vmImage: 'macOS-10.14'

resources:
  repositories:
  - repository: templates
    type: github
    name: cchanka/azdo-pipeline-templates
    endpoint: GitHub connection - cchanka


stages:
- template: build-dev-pipeline-template.yml@templates
