trigger:
- none

resources:
  repositories:
  - repository: templates
    type: github
    name: cchanka/azdo-pipeline-templates
    endpoint: GitHub connection - cchanka


jobs:
- template: pr-test-pipeline-template.yml@templates