pool:
  vmImage: 'macOS-10.14'

trigger: none

resources:
  repositories:
  - repository: templates
    type: github
    name: cchanka/azdo-pipeline-templates
    endpoint: GitHub connection - cchanka

stages:
- template: pr-test-pipeline-template.yml@templates