pool:
  vmImage: 'macOS-10.14'

trigger: none

stages:
  - stage: Test
    jobs:
      - job: Job_Test
        steps:
        - task: Gradle@2
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/TEST-*.xml'
            tasks: 'test jacocoTestReport'
          displayName: Run Unit Test and Generate Coverage Report

        - task: PublishCodeCoverageResults@1
          inputs:
            codeCoverageTool: 'JaCoCo' 
            summaryFileLocation: $(System.DefaultWorkingDirectory)/app/build/jacoco/jacocoTestReport/jacocoTestReport.xml
            reportDirectory: $(System.DefaultWorkingDirectory)/app/build/jacoco/jacocoTestReport/html
          displayName: Publish Test Coverage Report

        - task: Gradle@2
          inputs:
            workingDirectory: ''
            gradleWrapperFile: 'gradlew'
            gradleOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            tasks: 'jacocoTestCoverageVerification'
          env:
            JACOCO_MIN_LIMIT: $(JACOCO_MIN_LIMIT)
          displayName: Verify Test Coverage Min Limit
        

  - stage: Report_Results
    jobs:
      - job: Job_ReportResults
        steps:
        - bash: |
            echo Installing PyGithub...
            pip3 install PyGithub

            echo Reporting to Github...
            python3 .devops/devopsctl.py pr-comment update ${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER} "CICD: ${SYSTEM_PIPELINESTARTTIME}: Testing complete!"
          env:
            GITHUB_TOKEN: $(GITHUB_TOKEN)
          displayName: Reporting to Github PR
